In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a.dot(b)

In [3]:
print(c)

32


In [4]:
a

array([1, 2, 3])

In [5]:
print(a + b)
a + b       

[5 7 9]


array([5, 7, 9])

In [6]:
M = np.array([[1, 2], [3, 4]])
print(M)

[[1 2]
 [3 4]]


In [7]:
N = np.array([[5, 6], [7, 8]])
print(N)

[[5 6]
 [7 8]]


In [9]:
P = M @ N
print(P)

[[19 22]
 [43 50]]


In [10]:
A = np.matrix([a, b])
S = np.linalg.svd(A)
print(S)



SVDResult(U=matrix([[-0.3863177 , -0.92236578],
        [-0.92236578,  0.3863177 ]]), S=array([9.508032  , 0.77286964]), Vh=matrix([[-0.42866713, -0.56630692, -0.7039467 ],
        [ 0.80596391,  0.11238241, -0.58119908],
        [ 0.40824829, -0.81649658,  0.40824829]]))
